Milestone user interface
bren2102/Tic_Tac_Toe pull request #2
Opened 2020-02-26 16:48 UTC by MiguelDP4

- Created a game board array
- Created a method to print the game board
- Created mock game logic (intended to be transferred to a library in the next step)

2020-02-27 12:22 UTC, stratospherique requested changes
### Great work @team :clap: :clap: However, some requirements need to be implemented in order for us to approve your project. Check :arrow_down: 

##### Behaviour

* [ ] In this step not everything must work, the point is to make sure that students thought about everything listed below. They might do it only with inline comments. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [x] `[REQUIRED]` game tells which player turn it is
  * [x] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  
- You need to implement or just write in comments the logic related to verifying if a player move should halt the game (player wins or draw) or not.

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
_**Ahmed Mahfoudh**_

2020-02-27 12:22 UTC, stratospherique commented on bin/main
> +      board_array[number] = "O" if player_turn == 2
- **DRY** your code 

```suggestion
      board_array[number] = player_turn == 1 ? 'X' : 'Y'
```

2020-02-27 12:22 UTC, stratospherique commented on bin/main
> +  end
```suggestion
    player_turn = player_turn == 1 ? 2 : 1
```

2020-02-27 20:08 UTC, Forison requested changes
## Status: Require Changes🛑
# Hi team🙋‍♂️
Good job on implementing some of the changes raised in the previous review.
There are a few behavioral flaws that we have to address in this particular milestone.
* [x] game informs player if the selected move is a winning move.([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] game informs player if the selected move is a draw move ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x]  The game ends currently on the eighth moves. When the ninth move is the decider for a win or draws the game does not respond to accordingly. It is as if the ninth move is not taking into consideration by the game.
## That is it, kindly make this change and submit the project for review🙂
### Happy coding💻
### Addo Forison

2020-02-28 06:01 UTC, fatymahmed approved these changes
### Hi @MiguelDP4 @bren2102 ,
### Great job making the suggested changes🎉🎉
[OPTIONAL]
- Your main file should be `main.rb`
- Please do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from Pathwright. Use [these](https://github.com/microverseinc/linters-config/tree/master/ruby) config files.
### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-28 16:58 UTC, merged